#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  cLimit,         sensorTouch)
#pragma config(Sensor, dgtl2,  leftE,          sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  rightE,         sensorQuadEncoder)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intakeA,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           catapultA,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           intakeB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           catapultB,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightBack,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)


//_______________________________________________________________________________________________________________________________________________________________________________
// _____ _   _  _____ _      _    _ _____  ______  _____
//|_   _| \ | |/ ____| |    | |  | |  __ \|  ____|/ ____|
//  | | |  \| | |    | |    | |  | | |  | | |__  | (___
//  | | | . ` | |    | |    | |  | | |  | |  __|  \___ \.
// _| |_| |\  | |____| |____| |__| | |__| | |____ ____) |
//|_____|_| \_|\_____|______|\____/|_____/|______|_____/

#include "Vex_Competition_Includes.c"
#include "functions.h"
#include "routines.h"
#include "auton.h"


//_______________________________________________________________________________________________________________________________________________________________________________
//  _____  ____  _   _  _____ _______       _   _ _______ _____
// / ____|/ __ \| \ | |/ ____|__   __|/\   | \ | |__   __/ ____|
//| |    | |  | |  \| | (___    | |  /  \  |  \| |  | | | (___
//| |    | |  | | . ` |\___ \   | | / /\ \ | . ` |  | |  \___ \.
//| |____| |__| | |\  |____) |  | |/ ____ \| |\  |  | |  ____) |
// \_____|\____/|_| \_|_____/   |_/_/    \_\_| \_|  |_| |_____/

#define DEADZONE 20
#define CATAPULT_HOLD_POWER 15
int ARM_ZONE = 450;

//_______________________________________________________________________________________________________________________________________________________________________________
//  _____ _       ____  ____          _       _____
// / ____| |     / __ \|  _ \   /\   | |     / ____|
//| |  __| |    | |  | | |_) | /  \  | |    | (___
//| | |_ | |    | |  | |  _ < / /\ \ | |     \___ \.
//| |__| | |____| |__| | |_) / ____ \| |____ ____) |
// \_____|______|\____/|____/_/    \_\______|_____/


//CONTROL
int leftC = 0;
int rightC = 0;
int intakeC = 0;
int catapultC = 0;
int shootC = 0;

//FLAGS
int catapultCPrev = 0;
int chooseF = 1;
int chooseR = 0;
int dir = 1;

//MOTORS
int leftM = 0;
int rightM = 0;
int intakeM = 0;
int catapultM = 0;

//SENSORS
int cMaxLimit = 0;
int armPotV = 0;

void pre_auton() {
  bStopTasksBetweenModes = true;
}

task autonomous() {
  //int which_auton1 = SensorValue(a);
  //int which_auton2 = SensorValue(b);
  //int e = SensorValue(enable);
  //int done  = 0;
  //	if (which_auton1 == 1 && done == 0) {
  //		middleFlag();
  //		done = 1;
  //	}
  //	else if (which_auton2 == 1 && done == 0) {
  //		stopAllTasks();
  //		done = 1;
  //	}
  middleFlagImproved(
  );
  //forwardFlip(1700);
  //backwardsFlag(1700);
}

task usercontrol() {
  while (true) {

    //___________________________________________________________________________________________________________________________________________________________________________
    //__      __________   _______ _______
    //\ \    / /  ____\ \ / /  __ \__   __|
    // \ \  / /| |__   \ V /| |__) | | |
    //  \ \/ / |  __|   > < |  _  /  | |
    //   \  /  | |____ / . \| | \ \  | |
    //    \/   |______/_/ \_\_|  \_\ |_|

    leftC = vexRT[Ch2];
    rightC = vexRT[Ch3];
    intakeC = vexRT[Btn5U] - vexRT[Btn5D];


    //cMaxLimit = SensorValue(cLimit);


    catapultC = vexRT[Btn6U];
    shootC = vexRT[Btn6D];
    catapultCPrev = catapultC;


    chooseF = vexRT[Btn8U];
    chooseR = vexRT[Btn8D];

    armPotV = SensorValue(armPot);


    //  _____  ____  _   _ _______ _____   ____  _
    // / ____|/ __ \| \ | |__   __|  __ \ / __ \| |
    //| |    | |  | |  \| |  | |  | |__) | |  | | |
    //| |    | |  | | . ` |  | |  |  _  /| |  | | |
    //| |____| |__| | |\  |  | |  | | \ \| |__| | |____
    // \_____|\____/|_| \_|  |_|  |_|  \_\\____/|______|

    if(abs(leftC) > DEADZONE)
      leftM = leftC;
    else
      leftM = 0;

    if(abs(rightC) > DEADZONE)
      rightM = rightC;
    else
      rightM = 0;

    if(armPotV < ARM_ZONE)
      cMaxLimit = 1;
    else
      cMaxLimit = 0;

    if(chooseF == 1)
      dir = 1;
    else if (chooseR == 1)
      dir = 0;

    if(cMaxLimit == 0)
      catapultM = 120;
    else if(shootC == 1)
      catapultM = 120;
    else
      catapultM = CATAPULT_HOLD_POWER;

    if(catapultC == 1)
      catapultM = 0;


    intakeM = 128*intakeC;
    /*
    if(catapultC == 1 && cMaxLimit == 0) {
    catapultM = 120;
    } else if(catapultC == 1 && cMaxLimit == 1) {
    catapultM = 5;
    } else if(vexRT[Btn6D] == 1) {
    catapultM = 120;
    } else {
    catapultM = 0;
    } */

    // __  __  ____ _______ ____  _____   _____
    //|  \/  |/ __ \__   __/ __ \|  __ \ / ____|
    //| \  / | |  | | | | | |  | | |__) | (___
    //| |\/| | |  | | | | | |  | |  _  / \___ \.
    //| |  | | |__| | | | | |__| | | \ \ ____) |
    //|_|  |_|\____/  |_|  \____/|_|  \_\_____/


    setIntakeMotors(intakeM);

    if(dir)
      setDriveMotors(leftM, rightM);
    else
      setDriveMotors(-rightM, -leftM);

    setCatapultMotors(catapultM);

  }
}
